name: poly_live
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  http: ^0.13.5
  logging: ^1.1.1
  crypto: ^3.0.2
    # ui related
  pull_to_refresh: ^2.0.0
  responsive_builder: ^0.5.0+1
  flutter_staggered_grid_view: ^0.6.2
  # utils
  provider: ^6.0.5
  path_provider: ^2.0.12
  path_provider_foundation: ^2.1.1
  shared_preferences: ^2.0.17
  flutter_cache_manager: ^3.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

