name: poly_live
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  http: ^0.13.5
  logging: ^1.1.1
  crypto: ^3.0.2
  # Video
  video_player: ^2.5.1
  chewie: ^1.4.0
  # video player needed
  better_player: ^0.0.83
  flutter_barrage: ^0.5.2
  screen_brightness: ^0.2.2
  volume_controller: ^2.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

